/// Flutter icons CinappIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CinappIcons
///      fonts:
///       - asset: fonts/CinappIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CinappIcons {
  CinappIcons._();

  static const _kFontFam = 'CinappIcons';
  static const String? _kFontPkg = null;

  static const IconData bi_people_ico =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_ico =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_ico =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maki_cinema_ico =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_ico =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_ico =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signout_ico =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
